In [1]:
import math
import numpy as np

family = ("イシノミ目","シミ目","カゲロウ","トンボ目","カワゲラ目",
          "シロアリ目","ゴキブリ目","カマキリ目","ガロアムシ目","ナナフシ目",
          "シロアリモドキ目","バッタ目","ハサミムシ目","ジュズヒゲムシ目",
          "チャタテムシ目","シラム目","アザミウマ目","カメムシ亜目",
          "ヨコバイ亜目","アミメカゲロウ目","ラクダムシ目","ヘビトンボ目",
          "コウチュウ目","ネジレバエ目","ハエ目","シリアゲムシ目","ノミ目","トビゲラ目","チョウ目","ハチ目")

Itiigashi = (0,1,1,6,0,1,0,0,0,0,0,0,0,0,1,0,1,1,9,0,1,0,18,0,183,1,0,3,1,14)
Yurinoki = (0,0,0,0,0,0,0,0,0,0,0,1,0,0,2,0,0,3,12,1,0,0,2,0,57,0,0,0,1,10)
Someiyoshino = (0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,3,3,18,0,1,0,2,0,104,11,0,0,1,4)
GrassA = (0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,13,0,130,0,0,0,2,0,45,0,0,0,0,6)
GrassB = (0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,5,2,54,0,0,0,4,0,183,0,0,0,0,10)

results = [Itiigashi, Yurinoki, Someiyoshino, GrassA, GrassB]
SUM = [sum(Itiigashi),sum(Yurinoki),sum(Someiyoshino),sum(GrassA),sum(GrassB)]

In [2]:
H = np.zeros(5)

In [3]:
for i in range(0, 5):

    for num in results[i]:
        if num == 0:
            continue
        else:
            H[i] += -(num/SUM[i])*math.log(num/SUM[i], 2)    

In [4]:
Lambda = np.zeros(5)

In [5]:
for i in range(0, 5):

    for num in results[i]:
        if num == 0:
            continue
        else:    
            Lambda[i] += (num/SUM[i])*((num-1)/SUM[i])
        

In [6]:
Lambda

array([0.57888805, 0.43226865, 0.50922206, 0.46924581, 0.53689349])

In [7]:
Simp = np.ones(5)/Lambda

In [8]:
Simp

array([1.72744971, 2.31337617, 1.96377981, 2.13107923, 1.86256682])

In [9]:
C = np.zeros((5, 5))

In [10]:
for i in range(0, 5):
    
    for j in range(i, 5):
        
        for k in range(0, len(results[i])):
            C[i][j] += results[i][k]*results[j][k]*2/((Lambda[i]+Lambda[j])*SUM[i]*SUM[j])
            

In [11]:
C

array([[1.00713822, 0.98455833, 0.99071759, 0.37416153, 0.97417598],
       [0.        , 1.02599299, 0.99957136, 0.52011534, 0.99855474],
       [0.        , 0.        , 1.01326878, 0.48695417, 0.997304  ],
       [0.        , 0.        , 0.        , 1.01060238, 0.58530826],
       [0.        , 0.        , 0.        , 0.        , 1.00716372]])

In [12]:
ED = np.zeros((5,5))

for i in range(0, 5):
    
    for j in range(i, 5):
        
        for k in range(0, len(results[i])):
            ED[i][j] += (results[i][k]-results[j][k])**2
            
        ED[i][j] = ED[i][j]**(1/2)    

In [13]:
ED

array([[  0.        , 127.33813254,  82.68010643, 185.00540533,
         48.02082881],
       [  0.        ,   0.        ,  49.18333051, 119.51568935,
        132.93983602],
       [  0.        ,   0.        ,   0.        , 127.62053126,
         87.80660567],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        157.91453385],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ]])

In [18]:
ED.sort()

for i in range(0,len(ED)):
    if ED[i] != 0:
        break

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()