In [2]:
import numpy as np

X = np.matrix([[3,4],[2,7]])
X

matrix([[3, 4],
        [2, 7]])

In [3]:
X.I

matrix([[ 0.53846154, -0.30769231],
        [-0.15384615,  0.23076923]])

In [4]:
X*X.I

matrix([[1., 0.],
        [0., 1.]])